### PR TITLE
Check for `res.headersSent`

### PR DESCRIPTION
**Pull request by roblav96**
@lukeed

### CODE REVIEW

**Comment by lukeed** [comment]
Again, what's the purpose for this? 

> You don't have to ping me, haha. It's my repo so I get the notifications already 😀

**Comment by roblav96** [comment]
Apologies for the ping 😄

It's in the [response.headersSent](https://nodejs.org/api/http.html#http_response_headerssent) spec so I figured it should be included.

**Comment by lukeed** [comment]
Haha no worries, just trying to save you some typing~

I gave this a couple of different spins to test it out. While it _mostly_ had no effect, it does actually prevent this scenario:

```js
polka()
  .use((req, res, next) => {
    // write the head first
    res.writeHead(201, { 'x-hello': 'world' });
  })
  .get('/', (req, res) => {
    res.end('done'); // never reaches
  });
```

While this is generally pretty weird, I have seen this setup in the past. And, more seriously, a response still requires to be finished somewhere along the pipeline. So if you shutoff access to rest of the pipeline, you'll kill the server with a timeout error.

Also, if we add a `next()` call beneath the `writeHead` in this PR (as we should), we'll throw an Error immediately because we're effectively iterating the middleware loop by two counts. Writing this in the current `master` behaves as expected.

I'll do some more reading in the morning, but I'm 99% sure we need to continue tracking by the `res.finished` value only, simply because the Server itself is _also_ waiting on that in order for a response stream to be closed & considered successful.

**Comment by roblav96** [comment]
You my friend are very good! I was unaware you could even call `end` after `writeHead `. Thanks for the review! =]

**Comment by lukeed** [comment]
Hahaha why thank you~! For a long time I thought it was the only way to write headers & a status code 😆

**Pull request closed without merging**
