### PR TITLE
Fix Polka path in benchmark

### PR DESCRIPTION
**Pull request by icebob**
Hi @lukeed,
It fixes polka's path in benchmark test. 
> By the way, polka is the fastest, good job! :)

### CODE REVIEW

**Comment by lukeed** [comment]
I actually have a version in the works that's faster 🤫Slowly working towards a 1.0

**Comment by icebob** [comment]
Wow, awesome! :) And it will stay Express-compatible?

**Comment by lukeed** [comment]
It will be _more_ Express-compatible than it is now.

**Comment by icebob** [comment]
Cool! When do you plan to release this new version?

**Comment by lukeed** [comment]
Likely January, given my current time constraints. It also just happens to be the 1-year anniversary of Polka hah

**Comment by icebob** [comment]
Great! I'm looking forward to it.
_I'm planning to change my native http server solution in my API Gateway to polka in order to be faster._

**Pull request merged**
