### PR TITLE
perf(compression): use regex exec instead of match

### PR DESCRIPTION
**Pull request by bluwy**
I was running `eslint-plugin-regexp` in polka and found we can refactor the `str.match(re)` to `re.exec(str)` for perf.

```
/Users/bjorn/Work/oss/vite/node_modules/.pnpm/@polka+compression@1.0.0-next.25/node_modules/@polka/compression/build.js
  30:32  error  Use the `RegExp#exec()` method instead  regexp/prefer-regexp-exec
  30:68  error  Use the `RegExp#exec()` method instead  regexp/prefer-regexp-exec
```

I made some tests and can confirm there's a sizable perf improvement with exec. ([perf.link test](https://perf.link/#eyJpZCI6IndtaW0yb2VtNXU5IiwidGl0bGUiOiJyZWdleCBleGVjIHZzIG1hdGNoIiwiYmVmb3JlIjoiY29uc3QgcmUgPSAvXFxiYnJcXGIvXG5jb25zdCBzdHJzID0gQXJyYXkuZnJvbSh7IGxlbmd0aDogMTAwMCB9KS5tYXAoXyA9PiBNYXRoLnJhbmRvbSgpLnRvU3RyaW5nKDM2KS5zbGljZSgyKSkiLCJ0ZXN0cyI6W3sibmFtZSI6ImV4ZWMiLCJjb2RlIjoic3Rycy5mb3JFYWNoKHMgPT4geyByZS5leGVjKHMpIH0pIiwicnVucyI6WzE3MDAwLDExMDAwLDQ5MDAwLDUwMDAsMTAwMCw4NjAwMCwxMzkwMDAsMTAwMCw3MTAwMCwxMDAwLDE4NDAwMCwxMDAwLDExMjAwMCwxMDMwMDAsMTIyMDAwLDE2NTAwMCwxNjYwMDAsMTUxMDAwLDEwMDAsMTAwMCwxMDAwLDgwMDAsMTI1MDAwLDEyMDAwMCwxMzEwMDAsMTAwMCwzMDAwLDEwMDAsMTQ2MDAwLDUyMDAwLDI5MDAwLDM3MDAwLDE2MTAwMCwxMTYwMDAsMTI2MDAwLDEwMDAsMTAwMCwxNzAwMDAsODAwMCwxNTYwMDAsMTAwMCwxMDAwLDgxMDAwLDEwMDAsMTAwMCwzNjAwMCwxMDAwLDEzMjAwMCwxMDAwLDEwMDAsMjAwMCw0NjAwMCwxMDAwLDEyNTAwMCwxMDAwLDg1MDAwLDg4MDAwLDEwMDAsODIwMDAsMTAwMCw2MDAwLDE1ODAwMCwxMDAwLDE1NTAwMCwzMTAwMCwxMDAwLDgxMDAwLDEwMDAsNDAwMCw3NTAwMCwxMDAwLDQ1MDAwLDEwMDAsNzgwMDAsMTE3MDAwLDEwMDAsOTYwMDAsMTAwMCwzMjAwMCwxMDAwLDEwMDAsMjAwMCw3NjAwMCw1NTAwMCwzNTAwMCwxMjAwMDAsMjEwMDAsNDUwMDAsODYwMDAsOTQwMDAsNDcwMDAsODAwMDAsMjAwMCwzMzAwMCwxMTAwMCw5NjAwMCwxMDAwLDExMzAwMCwxMDAwLDMxMDAwXSwib3BzIjo1MzA0MH0seyJuYW1lIjoibWF0Y2giLCJjb2RlIjoic3Rycy5mb3JFYWNoKHMgPT4geyBzLm1hdGNoKHJlKSB9KSIsInJ1bnMiOlszMDAwLDEwMDAsMTAwMCwxMDAwLDEwMDAsMTMwMDAsMTYwMDAsNDAwMCw5MDAwLDE3MDAwLDEwMDAsMTAwMCwxNTAwMCwxNzAwMCwxOTAwMCwxMDAwLDEwMDAsMTAwMCwxMDAwLDEwMDAsMjAwMDAsMzAwMCwxMDAwMCwxMzAwMCwxNjAwMCwxNjAwMCwxMzAwMCwxNjAwMCwxMzAwMCwxMDAwLDUwMDAsMTEwMDAsMTMwMDAsMTAwMCwxNzAwMCwxMDAwLDEzMDAwLDExMDAwLDMwMDAsMTQwMDAsMTIwMDAsMTAwMCwxMzAwMCwxODAwMCwxMDAwLDcwMDAsMTUwMDAsMTIwMDAsMTUwMDAsMTgwMDAsMTAwMCwxMDAwMCwxODAwMCwxMDAwLDEwMDAsMTEwMDAsMTAwMCwxMDAwLDExMDAwLDEwMDAsMjAwMCwxMDAwLDEwMDAsMTEwMDAsOTAwMCwxMDAwLDEzMDAwLDEwMDAsMzAwMCw5MDAwLDEwMDAsOTAwMCwxMDAwLDE2MDAwLDEzMDAwLDEwMDAsNjAwMCwxMDAwLDEwMDAsMTUwMDAsMTYwMDAsMTYwMDAsMjAwMCwxMDAwLDYwMDAsMTYwMDAsNDAwMCwxMzAwMCwxMTAwMCwxNDAwMCwzMDAwLDEyMDAwLDEwMDAsMjAwMCw0MDAwLDcwMDAsMTAwMCw3MDAwLDE2MDAwLDcwMDBdLCJvcHMiOjc3NjB9XSwidXBkYXRlZCI6IjIwMjQtMDctMjZUMDk6MjM6MDAuNTUxWiJ9))

### CODE REVIEW

**Comment by kurtextrem** [comment]
might make sense to hoist the regexps too?

**Comment by bluwy** [comment]
The perf improvement from hoisting regex varies quite a bit in my experience and often doesn't yield noticable returns. I think engines are able to optimize them well enough these days. Maybe those with `g` flags could still be useful to hoist as they're more stateful.

**Comment by lukeed** [comment]
released as `@polka/compression@1.0.0-next.26`, ty @bluwy

**Comment by kurtextrem** [comment]
@bluwy Last time we benched it for valibot, it was ~2ms faster to hoist (even non global regexps)

**Comment by bluwy** [comment]
Yeah it'll depend but it's often a very small amount that I've come to prefer not bugging libraries to hoist them unless really needed 😅

**Comment by lukeed** [comment]
It generally has a significant impact in repeat synchronous usage (eg loops), so seeing it in valibot makes sense. In an async-like callback (like here) it won’t matter much, especially with simple patterns

**Pull request merged**
