### PR TITLE
Export `Polka` class for extensibility

### PR DESCRIPTION
**Pull request by roblav96**
@lukeed 🤓

### CODE REVIEW

**Comment by lukeed** [comment]
Hey, what's the reason for this?

**Comment by lukeed** [comment]
Because honestly it's kinda pointless. And it opens the door for people to use this in ways it's not designed for, and I don't want to support questions that come form those custom instances.

This, instead, can just be this:

```js
const polka = require('polka');

module.exports = function () {
  let app = polka();
  app.hook = fn => app.use((req, res, next) => fn(req, res).then(next, next));
  return app;
}
```

Extending the class is just adding extra overhead.

**Comment by roblav96** [comment]
That's why I didn't document it in the readme. lol

Right now I'm doing
```typescript
Object.assign(polka, {
	hook(this: any, handler: (req, res) => Promise<void>) {
		this.use(function(req, res, next) {
			handler(req, res).then(next).catch(next)
		})
	},
}
```
But then it make's type safety difficult.

**Comment by roblav96** [comment]
I can definitely understand that.

What if I did
```typescript
import * as Polka from 'polka'
class MyPolka extends Polka().constructor {
	// ...
}
```
Then reported a bajillion issues?? :P

You've made fair points, this PR will likely bring less good than bad in the long run.

**Comment by lukeed** [comment]
Haha I would be scared 😬

**Pull request closed without merging**
